### ISSUE TITLE
Horisontal blinds work

### ISSUE THREAD

**Issue by siggy2** [cornim/wms_webcontrol#2]
Hi, just wanted to report that I successfully integrated your code with HA and got my horisontal blind to work well. The only snag is that the percentage open/closed in the UI is reversed. It seems it is returning 100 when the blind is in while 0 when it is out. Logically it should be the other way around. In the WMS webcontrol app it shows correctly. For some reason it was reversed (100- position) in the HA integration code. By removing that, it just passes the actual position. I assume the vertical blinds were reversed for some reason. Maybe an idea to create an attribute for each entity whether to reverse or not?

**Comment by siggy2** [comment]
It would be super useful with an option to stop the blind after triggering either the opening or close action. Does Warema support that or would you need to pull current position and pass that position +/- 1 ?

Thanks a bunch for doing this btw. So cool to get this one integrated in my system.

**Comment by cornim** [comment]
Sorry for the late reply, I must have had notifications turned off at some point.

I did the implementation for vertical blinds so horizontal blinds having open/close settings reversed would not be suprising to me, given that the Warema implementation seems to be all over the place anyway.

When you say "stop the blind" are you taking about just stopping them where they are or stopping them at a particular point/setting, e.g. at 80% open. The later should already be supported. I'm not sure the former makes much sense due to the lag in the Warema system that I'm often experiencing when going via the WebControl interface.

**Comment by siggy2** [comment]
Hi, thanks for the reply. And yes, I was essentially referring to the command equivalent of the stop button (the percentage out is supported so that's OK)

**Comment by cornim** [comment]
I believe there are two major hurdles for that.
 1. The lag I mentioned. Typically I have about 1sec lag but sometimes the command needs to be resend as reception seems to be spotty and in those cases lag can go up to several seconds which would make a stop button problematic.
 2. As far as I can tell, HA doesn't have support for a stop button in their interface. Only open, close and position. Or has that changed in the mean time?

**Comment by siggy2** [comment]
As to the lag, that might be a problem although I seem to have pretty ok reception and limited lag. Given the time it takes at least for my shades to move I think that would still work. As to HA support for stop button, I have a stop button on my rflink controlled shades in HA, so support is there.Sigvart On Jan 19, 2022 09:53, Cornelius Mund ***@***.***> wrote:
I believe there are two major hurdles for that.
The lag I mentioned. Typically I have about 1sec lag but sometimes the command needs to be resend as reception seems to be spotty and in those cases lag can go up to several seconds which would make a stop button problematic.As far as I can tell, HA doesn't have support for a stop button in their interface. Only open, close and position. Or has that changed in the mean time?

**Comment by cornim** [comment]
Hi,
I added a stop cmd in the feat_shade_stop branch. I did the changes directly in GitHub so there might be some syntax error but in should in principle work.
Feel free to try it out.

**Comment by siggy2** [comment]
I will try it as soon as I get my webcontrol to work again. For some reason it can no longer comminicate with the shade. Do you by any change know where I can find an updated firmware for the we controller itself?

**Comment by cornim** [comment]
Sorry, no idea.
