### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [cornim/wms_webcontrol#5]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

Thanks

**Comment by cornim** [comment]
Sorry for the late reply, I must have had notifications turned off at some point.
Are you referring to a git tag?

**Comment by cornim** [comment]
I'm closing this for lack of reply.

**Comment by fabaff** [comment]
>  Are you referring to a git tag?

Yes, I do.

**Comment by cornim** [comment]
Done.
At least for the latest version. Do you need any other?

**Comment by fabaff** [comment]
> At least for the latest version. Do you need any other?

No, the latest is fine. Thanks

**Comment by fabaff** [comment]
0.2.3 is [tagged](https://github.com/cornim/wms_webcontrol/tags) but 0.2.4 not.
