### ISSUE TITLE
Error after Update HomeAssistant 2022.2

### ISSUE THREAD

**Issue by Stephan1908** [cornim/wms_webcontrol#7]
Hi,

I have updated home assistant to version 2022.2. Now I get an error message when starting, or I can't restart. When I check the configuration I get this error message: 

![grafik](https://user-images.githubusercontent.com/60405276/157012453-f1b58dbb-01d3-4bbd-9753-42d00502d755.png)

Greetings

**Comment by cornim** [comment]
That is already fixed in my integration repo (linked in the README). Just update.

**Comment by Stephan1908** [comment]
Thank You!
Now It works again.
